In [1]:
import numpy as np

# NUMPY BASIC

-----------

**(1). The value Range(0,10) ,  convert the list to `2D array`.**

In [2]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

-------------------------------------------------------------

**(2).Print or show only 3 decimal places of the numpy array `random_arr`**

In [3]:
a = np.random.rand(5);
print(np.around(a,3))

[0.928 0.438 0.905 0.074 0.534]


----------------------------------

**(3).The number of items printed to be limit in python numpy array a to a maximum of 6 elements.**

   
     Intake : x = np.arange(15)
               array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
               
     Result : ([ 0,  1,  2, ..., 12, 13, 14])

In [4]:
    #np.set_printoptions(threshold=5)
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**(4). An arrays of `x` and `y` , Stack the `x` and `y` arrays Horizontal.**


    Intake:
                x = np.arange(10).reshape(2,-1)

                y = np.repeat(1, 10).reshape(2,-1)

 
    
    Result:       ([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
                   [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [5]:
x = np.arange(10).reshape(2,-1);
y = np.repeat(1,10).reshape(2,-1);
a = np.hstack((x,y))
print(a)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


----------------------

**(5). There are two array `x` and `y` ,output to be the matching items in both the array.**
    
    
    Intake: 
   
        x = np.array([1,2,3,2,3,4,3,4,5,6])
        y = np.array([7,2,10,2,7,4,9,4,9,8])
 
    Results:
        
         ([2, 4])
            
    

In [6]:
x = np.array([1,2,3,2,3,4,3,4,5,6]);print(x)
y = np.array([7,2,10,2,7,4,9,4,9,8]);print(y)
list1 = []
for i in x:
    for j in y:
        if i == j:
            list1.append(i)

my_set = set(list1)
print(my_set)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
{2, 4}


---------------------

**(6). There are two array x and y ,drop the items in `X` which already exist in `Y`.**

   
    INTAKE:
     x = np.array([1,2,3,4,5])
     y = np.array([5,6,7,8,9])
    
    
    RESULT:
     ([1,2,3,4])
        
    

In [7]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])
c = []
for i in x:
    for j in y:
        if i != j:
            c.append(i)
        else:
            break
        
my_set = set(c)
print(my_set)

{1, 2, 3, 4}


--------------------------

**(7). Reverse the rows of a 2D array.**


    Intake : X = np.arange(9).reshape(3,3)
    
    Result :      ([[6, 7, 8],
                    [3, 4, 5],
                    [0, 1, 2]])

In [8]:
x = np.arange(9).reshape(3,3)
x[:,:] = np.flip(x[:,:])
x[2] = np.flip(x[2])
x[1] = np.flip(x[1])
x[0] = np.flip(x[0])
print(x)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


----------------------

**(8). Reverse the columns of a 2D array.**

    Intake : X = np.arange(9).reshape(3,3)
    
    Result :     ([[2, 1, 0],
                   [5, 4, 3],
                   [8, 7, 6]])


In [9]:
x = np.arange(9).reshape(3,3)
x[0] = np.flip(x[0])
x[2] = np.flip(x[2])
print(x)

[[2 1 0]
 [3 4 5]
 [8 7 6]]


---------------------

**(9). Print the ranks for the given numeric array `x`.**
 
   
    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=10)
    print(x)
    [ 9  4 15  0 17 16 17  8  9  0]
    
    
    Result:
    [4 2 6 0 8 7 9 3 5 1]
    

In [10]:
np.random.seed(10)
x = np.random.randint(1,20,size=10)
order = x.argsort()
ranks = order.argsort()
print(x)
print(ranks)

[10  5 16  1 18 17 18  9 10  1]
[4 2 6 0 8 7 9 3 5 1]


--------------------

**(10). Print a rank array of the same shape as a given numeric array `x`.**


    Intake:
    np.random.seed(10)
    x = np.random.randint(20, size=[2,5])
    print(a)
    [[ 9  4 15  0 17]
    [16 17  8  9  0]]
    
    Result:
    [[4 2 6 0 8]
    [7 9 3 5 1]]

In [11]:
x = np.random.randint(20,size=[2,5])
order = x.argsort()
ranks = order.argsort()
print(x)

print(ranks)

[[10  8  4 19 16]
 [ 4 15 11 11  1]]
[[2 1 0 4 3]
 [1 4 2 3 0]]


--------------------------------

**(11). Subtract the 1d array y_1d from the 2d array x_2d, such that each item of y_1d subtracts from respective row of x_2d.**
    
    Intake:
    x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
    y_1d = np.array([1,2,3])
    
    Result:
     [[2 2 2]
     [2 2 2]
     [2 2 2]]

In [12]:
x_2d = np.array([[3,3,3],[4,4,4],[5,5,5]]);
y_1d = np.array([1,2,3]).reshape(3,1);
z = x_2d - y_1d
print(z)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [13]:
print(np.__version__)

1.15.4


In [14]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


----------------

# ----------------------------------HAPPY LEARNING--------------------------------------------------

-------------------